egranata/aria

- .github/workflows/rust.yml
- t
On every merge and every pull request, build and test the project
> Turn on automatic builds

- parser-lib/src/ast/nodes/code_block.rs
- parser-lib/src/grammar/grammar.pest
- tests/if_assign_val.aria
> Fix parse of variable write with "val" prefix

- aria-bin/src/main.rs
- tests/str_len_vs_index.aria
- vm-lib/src/runtime_value/string.rs
> Fix String length to use characters, not bytes

- compiler-lib/src/do_compile/nodes/lambda.rs
- compiler-lib/src/do_compile/nodes/return_statement.rs
- parser-lib/src/ast/mod.rs
- parser-lib/src/ast/nodes/return_statement.rs
- parser-lib/src/grammar/grammar.pest
- tests/naked_return.aria
> Allow return with no expression

- native-libs/path/src/lib.rs
- tests/dir_entries.aria
- tests/path_canonical.aria
> Path.new_canonical returns a Maybe if it cannot resolve the path

- docs/stdlib.md
- lib/aria/core/int.aria
- tests/parse_int.aria
36 allows 10 digits and 26 alphabet letters. Allow parsing more than just
decimal integers
> Implement int parsing of arbitrary (<=36) base

- compiler-lib/src/do_compile/mod.rs
- compiler-lib/src/do_compile/nodes/function_decl.rs
- compiler-lib/src/do_compile/nodes/lambda.rs
- compiler-lib/src/do_compile/nodes/method_decl.rs
- parser-lib/src/ast/mod.rs
- parser-lib/src/ast/nodes/argument_list.rs
- parser-lib/src/ast/nodes/function_decl.rs
- parser-lib/src/ast/nodes/method_decl.rs
- parser-lib/src/ast/nodes/operator_decl.rs
- parser-lib/src/grammar/grammar.pest
- vm-lib/src/vm.rs
This series improves some of the code that compiles functions/methods
It is done in preparation for #93
> Improvements to function compilation

- lib/aria/core/arity.aria
- lib/aria/core/builtin.aria
- tests/function_arity.aria
- vm-lib/src/builtins/arity.rs
- vm-lib/src/builtins/mod.rs
- vm-lib/src/runtime_value/object.rs
- vm-lib/src/vm.rs
> Add support for an API to discover the arity of an arbitrary function

- lib/aria/network/retry.aria
- tests/http_get_headers.aria
- tests/http_post.aria
- tests/http_post_json.aria
- tests/request_custom_status.aria
- tests/retry_test.aria
- tests/simple_http_get.aria
- tests/sleep.aria
- vm-lib/src/builtins/mod.rs
- vm-lib/src/builtins/sleep.rs
- vm-lib/src/error/exception.rs
> Allow retries of web requests in Aria tests

- compiler-lib/src/do_compile/mod.rs
- compiler-lib/src/do_compile/nodes/function_body.rs
- compiler-lib/src/do_compile/nodes/lambda.rs
- compiler-lib/src/do_compile/nodes/mod.rs
- docs/manual.md
- parser-lib/src/ast/mod.rs
- parser-lib/src/ast/nodes/function_body.rs
- parser-lib/src/ast/nodes/function_decl.rs
- parser-lib/src/ast/nodes/method_decl.rs
- parser-lib/src/ast/nodes/mod.rs
- parser-lib/src/ast/nodes/operator_decl.rs
- parser-lib/src/grammar/grammar.pest
- tests/one_line_function.aria
> Add support for one-liner functions, methods and operator overloads

- aria-bin/src/error_reporting.rs
- test-bin/src/main.rs
- vm-lib/src/frame.rs
- vm-lib/src/vm.rs
A default empty frame needs 0 locals, not 255
> Fix up default frame creation

- lib/aria/json/writer.aria
- lib/aria/network/request.aria
- lib/aria/structures/set.aria
- tests/custom_to_json_value.aria
- tests/set_ops.aria
- tests/to_json_value.aria
new_with is sanctioned by the style guide, new_from is not
> Replace new_from with new_with

- docs/stdlib.md
- examples/dir.aria
- lib/aria/date/instant.aria
- tests/dir_entries.aria
- tests/instant_from_unix_2024_12_29.aria
- tests/instant_from_unix_ts.aria
- tests/instant_with_tz_offset.aria
> Fix up Instant API

- compiler-lib/src/do_compile/postfix.rs
- lib/aria/range/range.aria
- lib/aria/rng/msws.aria
- lib/aria/structures/map.aria
- lib/aria/structures/queue.aria
- lib/aria/structures/set.aria
- lib/aria/structures/stack.aria
- lib/aria/system/coloring.aria
- parser-lib/src/ast/mod.rs
- parser-lib/src/ast/nodes/postfix_term_field_set.rs
- parser-lib/src/grammar/grammar.pest
- tests/dot_write_of_local.aria
- tests/nested_obj_write.aria
> Allow short-hand initializer syntax

- .github/workflows/release.yml
- package.sh
- **Create a script that will package up a build of Aria into a .tgz file**
- **Create a github workflow to package Aria releases when a new tag is pushed**
> Create a way to deliver installable Aria packages

- Cargo.toml
- package.sh
- **Introduce dist/release profile**
- **Add docs and examples to the Aria prebuilt packages**
> Improvements to prebuilt packaging

- compiler-lib/src/dump/opcodes.rs
- docs/manual.md
- docs/stdlib.md
- docs/style_guide.md
- lib/aria/core/builtin.aria
- lib/aria/core/result.aria
- lib/aria/iterator/mixin.aria
- opcodes-lib/src/lib.rs
- tests/flatten_results.aria
- tests/result.aria
- tests/result_helpers.aria
- tests/result_to_exception.aria
- vm-lib/src/builtins/mod.rs
- vm-lib/src/builtins/result.aria
- vm-lib/src/vm.rs
> Implement Result type

- README.md
- examples/advent_of_code_2024_day3.aria
- examples/currency.aria
- examples/parser.aria
- examples/string_escapes.aria
- lib/aria/core/float.aria
- lib/aria/core/int.aria
- lib/aria/core/string.aria
- lib/aria/json/parser.aria
- lib/aria/numerics/decimal.aria
- lib/aria/system/coloring.aria
- tests/builtin_type_func_takes_This.aria
- tests/decimal.aria
- tests/decimal_prettyprint.aria
- tests/parse_fp.aria
- tests/parse_int.aria
- vm-lib/src/builtins/result.aria
> Use Result instead of Maybe for parsing numeric values

- lib/aria/json/parser.aria
- lib/aria/json/writer.aria
- lib/aria/network/request.aria
- tests/custom_to_json_value.aria
- tests/http_get_headers.aria
- tests/http_post.aria
- tests/http_post_json.aria
- tests/json_flatten.aria
- tests/json_parse_array.aria
- tests/json_parse_nested.aria
- tests/json_parse_wellknown.aria
- tests/simple_json_parse.aria
- tests/simple_json_parse_err.aria
- tests/to_json_string.aria
- tests/to_json_value.aria
> Use Result in Json reading and writing

- docs/stdlib.md
- lib/aria/io/path.aria
- native-libs/path/src/lib.rs
- tests/dir_entries.aria
- tests/path_common_ancestor.aria
> Add operations to aria.io.Path

- ci_tests.sh
- tests/http_get_headers.aria
- tests/http_post.aria
- tests/http_post_json.aria
- tests/http_request_custom_status.aria
- tests/http_simple_get.aria
> Re-enable HTTP tests

- vm-lib/src/error/vm_error.rs
- vm-lib/src/test.rs
- vm-lib/src/vm.rs
> Allow main to receive its command line arguments directly
